name: compile
on:
  push:
    branches:
      - master
      - main
env:
  LATEX_ROOT: cilc-2022-logic-api-ml
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
          
      - name: Build latex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ env.LATEX_ROOT }}.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape
          
      - name: Get Time
        id: current-time
        run: echo "::set-output name=time::$(date +'%Y.%m.%d+%H-%M-%S')"

      - name: Install PDFtk
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pdftk

      - name: Split PDF file
        env:
          RELEASE_TAG: ${{ steps.current-time.outputs.time }}
        run: |
          pdftk F=$LATEX_ROOT.pdf cat F1-12 output paper-$RELEASE_TAG.pdf
          pdftk F=$LATEX_ROOT.pdf cat F13-end output supplementary-$RELEASE_TAG.pdf
        
      - name: Release Assets
        id: upload-release-asset
        env:
          RELEASE_TAG: ${{ steps.current-time.outputs.time }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          ASSETS=()
          for A in *.pdf; do
            ASSETS+=("-a" "$A")
            echo "Releasing $A"
          done
          hub release create "${ASSETS[@]}" -m "$RELEASE_TAG" "$RELEASE_TAG"
