name: compile
on:
  push:
    branches:
      - master
      - main
env:
  LATEX_ROOT: kr-MlLogicApi
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Build latex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ env.LATEX_ROOT }}.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape
        
      - name: Bump version
        id: bump-version
        uses: anothrNick/github-tag-action@1.22.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: true
          
      - name: Get Time
        id: current-time
        run: echo "::set-output name=time::$(date +'%Y-%m-%dT%H%M%S')"

      - name: Install PDFtk
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pdftk

      - name: Split PDF file
        env:
          RELEASE_TAG: ${{ steps.bump-version.outputs.new_tag }}-${{ steps.current-time.outputs.time }}
        run: |
          pdftk F=$LATEX_ROOT.pdf cat F1-10 output paper-$RELEASE_TAG.pdf
          pdftk F=$LATEX_ROOT.pdf cat F11-end output supplementary-$RELEASE_TAG.pdf
        
      - name: Release Assets
        id: upload-release-asset
        env:
          RELEASE_TAG: ${{ steps.bump-version.outputs.new_tag }}-${{ steps.current-time.outputs.time }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          ASSETS=()
          for A in *.pdf; do
            ASSETS+=("-a" "$A")
            echo "Releasing $A"
          done
          hub release create "${ASSETS[@]}" -m "$RELEASE_TAG" "$RELEASE_TAG"
